services:
  evalmusemini:
    build:
      context: .
      tags: 
        - "evalmusemini:main"
    container_name: evalmusemini
    network_mode: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
