metric:
  _target_: metric.ElementAlignmentMetric
metadata_path: /home/dmitrii/code/general-pipeline/submodules/EvalMuseMini/data/dataset/prompts.json
model_path: /home/dmitrii/code/general-pipeline/submodules/EvalMuseMini/pretrained_models/fga_blip2.pth
device: cpu