metric:
  _target_: metric.ElementAlignmentMetric
metadata_path: /app/data/generated_images/sd-legacy_stable-diffusion-v1-5/ivan_007/metadata.json
model_path: /app/pretrained_models/fga_blip2.pth
device: cpu